name: Terraform Pipeline Template

on:
  workflow_call:
    inputs:
      directories:
        required: true
        type: string
      wif_provider:
        required: true
        type: string
      service_account:
        required: true
        type: string

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        directory: ${{ fromJson(inputs.directories) }}
    defaults:
      run:
        working-directory: ${{ matrix.directory }}

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ inputs.wif_provider }}
          service_account: ${{ inputs.service_account }}

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
      - run: terraform plan -no-color

  apply:
    name: Terraform Apply
    needs: plan
    runs-on: ubuntu-latest
    environment: production # Trava de aprovação manual
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        directory: ${{ fromJson(inputs.directories) }}
    defaults:
      run:
        working-directory: ${{ matrix.directory }}

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ inputs.wif_provider }}
          service_account: ${{ inputs.service_account }}

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
      - run: terraform apply -auto-approve